### ISSUE TITLE
[Request] Community-driven tutorial?

### ISSUE THREAD

**Issue by alicerunsonfedora** [GanstaKingofSA/DDLCModTemplate2.0#1]
In response to some messages on DDMC Discord, we should make a Git submodule for this template with a community-written, community-driven version of the tutorial to replace the existing MAS one.

**Comment by GanstaKingofSA** [comment]
Will be worked on in conjunction with others.

**Comment by GanstaKingofSA** [comment]
Planned out a possible rough idea on the tutorial.

- Understandable, easy to follow and read tutorial on how to code DDLC
- Have Monika help the player out if they are stuck by opening the answer .txt files herself
- Add XCode Tutorial portion (conjunction with alicerunsonfedora) (shows if system is a Mac)
- NVL when added

**Comment by alicerunsonfedora** [comment]
Yeah, I can handle the Xcode portion of it. I'll need to see how everything else is written, though, before doing anything.

**Comment by GanstaKingofSA** [comment]
Tutorial Re-write was complete as of June 2020. Feedback for future tutorial referencing should be either here or it's new issue for now. Only re-writes not done but are removed temporarily will be the poem game and such as it still uses MAS leftover code.
