### ISSUE TITLE
DDLCRPAsMissing is Not Defined

### ISSUE THREAD

**Issue by epsseniyer** [GanstaKingofSA/DDLCModTemplate2.0#49]
**Describe the bug**
In Splash.rpy DDLCRPAsMissing is not defined and I'm already put rpa's in

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/66587693/191184934-ad00e4cd-5d58-444a-a64c-6d28c2c04759.png)
![image](https://user-images.githubusercontent.com/66587693/191184954-f44b566f-6eb6-4fd7-a71d-0d816f433a09.png)

**Additional context**

**Comment by Bronya-Rand** [comment]
Which Mod Template Version?

**Comment by Bronya-Rand** [comment]
Due to inactivity and verification that recent templates do have the file associated with the given exceptions, closing thread.
