### ISSUE TITLE
New Poem Responses "poems.rpy" doesn't call the tutorial image to dismiss the poem for the first time.

### ISSUE THREAD

**Issue by cpgyuri** [GanstaKingofSA/DDLCModTemplate2.0#67]
The new function to call poems in the poems.rpy file of the 4.2.1 template doesn't have the code snippet of the previous template to call the tutorial image to dismiss the poem if it's the first time for you to see one, which is a staple of the previous templates and the original game.

This is the code snippet in the previous template file
![image](https://user-images.githubusercontent.com/40330209/224084692-0886b8f8-5a71-4add-9bb1-e61358a9d041.png)

This is the image I'm talking about
![poem_dismiss](https://user-images.githubusercontent.com/40330209/224085382-3a3b61bf-f001-4d2f-b70f-b2242afb3303.png)

For the esthetics of the GUI and elements I have for Yuri Lavender Adventure, I have replaced this little image for the first poem which appears on screen
![poem_dismiss](https://user-images.githubusercontent.com/40330209/224085557-ccb8e2bf-b5fd-471f-afb0-f7bad9ea3a4e.png)

, but now I don't have a way to show it, and I don't feel confident enough to manipulate the code to add the code snippet back in. Please re-add the option back in, thank you.

**Comment by Bronya-Rand** [comment]
re-added
