### ISSUE TITLE
Renpy doesn't know Modal???

### ISSUE THREAD

**Issue by Ineedalottahelp** [GanstaKingofSA/DDLCModTemplate2.0#70]
So I followed the steps in the https://ddlc-modding.fandom.com/wiki/Quick_Start_Guide#Installing_Renpy website. When I press "Launch Project" in Renpy, it says "File "game/poem_responses/poems.rpy ", line 766: style property modal is not known."

**Comment by Bronya-Rand** [comment]
What version of Ren'Py are you using?

**Comment by Bronya-Rand** [comment]
Closing as no response was given. This is probably due to using the template on Ren'Py 6 which has been starting to be depreciated over time.
