### ISSUE TITLE
name 'Achievement' not defined

### ISSUE THREAD

**Issue by StriderYAA** [GanstaKingofSA/DDLCModTemplate2.0#71]
**Used Ren'py version:** 8.1.1
**Used Template:** DDLCModTemplate-4.2.2-Py3

Hey, sorry for bothering, I'm predicting that I missed a crucial step.

I had a break from modding DDLC, so I decided to try out the newer Mod Templates. While downloading, I took notice that the Extra's were now in a different package, so I downloaded that as well.

After putting _"audio.rpa"_, _"images.rpa"_ and _"fonts.rpa"_ to the now unzipped Mod Template, everything worked as expected. Next, I attempted to install the Extras (Only achievements, gallery and the extras screen).

**The _"readme.md"_ file reads:** "For most code here, all you need to do is copy the respective feature files inside their folders to your projects' game folder."

So, I checked if any of the three had extra instructions, none of them turned out to have any, so I just put _"achievements.rpy"_, _"gallery.rpy"_ and _"extras_screen.rpy"_ directly into the "game" folder in the template. When I tried to run the mod again an execption occured. Full traceback is attached. [traceback.txt](https://github.com/GanstaKingofSA/DDLCModTemplate2.0/files/12242592/traceback.txt)

Then I tried to run it without _"achievements.rpy"_ and game started but the extras menu didn't show up.

I hope I gave enough information, and again sorry to bother.

**Comment by Bronya-Rand** [comment]
Will update comment possibly later but in regards to this, you also would have needed to activate some stuff in 0imports.rpy. Will re-see when I get the chance

**Comment by StriderYAA** [comment]
Ah, alright. I'm waiting.

**Comment by Bronya-Rand** [comment]
Patched 0imports.rpy to fix achievement issue. Will be part of 4.2.3 when all other issues clear up from the Issue list.

**Comment by StriderYAA** [comment]
Alrighty, thanks, man. Have a good day.
