### ISSUE TITLE
Error when launching the template

### ISSUE THREAD

**Issue by RosiePetals** [GanstaKingofSA/DDLCModTemplate2.0#72]
When launching the template, I get this error:

While running game code:
  File "game/definitions/splash.rpy", line 650, in script
    jump expression persistent.autoload
ScriptError: could not find label 'story_main'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/definitions/splash.rpy", line 650, in script
    jump expression persistent.autoload
  File "renpy/ast.py", line 1992, in execute
    rv = renpy.game.script.lookup(target)
  File "renpy/script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'story_main'.

I'm on renpy 7.6.1 and am using the 4.2.2 template.

**Comment by Bronya-Rand** [comment]
Try clearing persistent as it seems to have saved the label for a script that is no longer using that name.

**Comment by Bronya-Rand** [comment]
Closed due to inactivity for well over a month.
