### ISSUE TITLE
2 Bugs

### ISSUE THREAD

**Issue by VauntFremontTocsin** [GanstaKingofSA/DDLCModTemplate2.0#74]
**Bug 1**
swapping the menu sprites with assets in the mod assets folder results in only the edited locations of sayori's and monika's sprites showing up in the menu, in my instance they all share one sprite.

**To Reproduce Bug 1**
Just swap the normal menu sprite locations with sprites you have in the mod assets folder.

**Expected behavior for Bug 1**
I would think that swapping the sprites would show all 4 menu sprites.

**Screenshot for Bug 1**
![screenshot0001](https://github.com/GanstaKingofSA/DDLCModTemplate2.0/assets/62199437/3901103c-a3ed-4a09-94a7-8a97ad4873bc)

**Bug 2**
Povname + password function displays the text out of the dialog box.

**To Reproduce Bug 2**
Just simply using the provided script
    $ povname = renpy.input("What's {i}his{/i} name?", default="", length=20)
    $ povname = povname.strip()
    window hide

    if povname in ["example", "Example", "here", "Here"]:
        jump example_easteregg
    elif povname in ["oc", "Oc"]:
        jump oc_easteregg
    elif True:
        jump default_action

    $ password = renpy.input("top secret?")
    $ password = password.strip()
    if password == "TOPSECRET":
        scene webm_background
    elif True:
        jump ch0_kill

**Expected behavior for Bug 2**
I would i would expect the dialog for these to at the very least be at a text position like the normal dialog

**Screenshots for Bug 2**
![Untitled (2)](https://github.com/GanstaKingofSA/DDLCModTemplate2.0/assets/62199437/ff3edb5a-0cd0-4958-bfb2-005a551a0097)
![Untitled (3)](https://github.com/GanstaKingofSA/DDLCModTemplate2.0/assets/62199437/1ada7989-edc1-4159-99dd-87ee98744dcf)

**Comment by Bronya-Rand** [comment]
Bug 2 isn't really a bug as Dan never intended to use `renpy.input` as-is. This is more meant for other things in Ren'Py that you can adjust as-is.

I can try to see Bug 1 but AFAIK, I feel this is down to paths being marked wrong, file names or a accidental removal or a portion of code from the original game.

**Comment by VauntFremontTocsin** [comment]
Kinda a sudden with this Bug too but when using 4.2.2, for whatever reason, it won't read the path to my custom rpy

```
If persistent.playthrough == 1:
        call top_secret
    else:
        call top_secret
```
In my top_secret.rpy

```
label top_secret:
    "Insert text here."
```

![1j8myhf4p3pb1.png](https://github.com/GanstaKingofSA/DDLCModTemplate2.0/assets/62199437/251da434-8065-42b3-bcc6-4e1f175be511)

**Comment by Bronya-Rand** [comment]
By default you are in playthrough 0. Also, you forgot to remove the remove the dialog warning in script.rpy which is stated below and in the message how to remove and call upon your custom RPY.

This is not a bug. For more assistance, refer to the DDMC Discord or subreddit, not Github Issues unless its a actual template bug.

**Comment by Elckarow** [comment]
> By default you are in playthrough 0

whether the condition is true or not, they're calling the same label. but yes, they probably didn't remove the dialog screen call

**Comment by Bronya-Rand** [comment]
> whether the condition is true or not, they're calling the same label. but yes, they probably didn't remove the dialog screen call

Yes. That is true. It's more a FYI that their condition is at 0 but I didn't realize both goes to each label (derp on my part). They prob just didn't read the comments in the file telling people to remove the dialog call once their script is done.

**Comment by Bronya-Rand** [comment]
Closed due to inactivity.
