### ISSUE TITLE
Adding xalign 0.5 to the navigation buttons makes them shift in the settings menu

### ISSUE THREAD

**Issue by EqualsM3rc** [GanstaKingofSA/DDLCModTemplate2.0#75]
If you want your main menu buttons to be centered in relation to eachother, by adding an `xalign 0.5` in `style navigation_button_text` it makes it so when you go into the settings menu the buttons shift to the right. This happens (as far as I can tell) because you're reusing the style for the "DDLC Settings" and "Template Settings" from the navigation buttons, and somehow that interaction shifts the navigation. Giving the "DDLC Settings" and "Template Settings" its own separate style fixes the issue.

To Reproduce
Add `xalign 0.5` to `style navigation_button_text`

![image](https://github.com/GanstaKingofSA/DDLCModTemplate2.0/assets/37270449/84cfef97-639a-4cd0-873d-321569a8257f)

![image](https://github.com/GanstaKingofSA/DDLCModTemplate2.0/assets/37270449/d7b4e62b-6626-42a0-9ef0-0114c1b652a6)

**Comment by Bronya-Rand** [comment]
This is not necessarily a bug with the template nor DDLC itself. As the template is designed to be a skeleton framework to make mods, most code is made in consideration of a traditional DDLC UI layout. What you have is a side effect of your change when transition from the main menu to the game menu when accessing other layout pages.

**Comment by EqualsM3rc** [comment]
I see. I didn't actually discover this myself, but simply helped someone else fix it after they centered the buttons.
I thought it would maybe make sense to give those 2 buttons a separate style since that avoids the problem altogether.
But I'll leave it up to you if you want to change it or not.
Cheers
