### ISSUE TITLE
Right-to-Left Text Alignment Issue

### ISSUE THREAD

**Issue by Sudoku8** [GanstaKingofSA/DDLCModTemplate2.0#76]
I'm working on an Arabic translation of DDLC and I've run into a text alignment issue. Despite setting `renpy.config.rtl = True` for RTL support and applying `xalign 1.0` to the text styles, the text within the `poems.rpy` file is not aligning to the right as expected for Arabic script.

Steps taken:
- Confirmed `renpy.config.rtl = True` is set globally.
- Applied `xalign 1.0` to the text styles for poems.
- Expected the text to align right, but it's still left-aligned.

I'm using Ren'Py version [7.6.3], I'm attaching a screenshot directly to this issue for clarity.

![1](https://github.com/Bronya-Rand/DDLCModTemplate2.0/assets/134165442/331c8782-fcd5-4e0e-b263-fc29507a66d1)

I might not be in the right place, but your guidance on this would be really helpful.

**Comment by Bronya-Rand** [comment]
I'm unfamiliar with right-to-left text unfortunately as it isn't really something I have been asked about, nor do I know a language that is Right to Left than Left to Right.

All I can really say here is that you may want to make a custom style and see if you can get right to left to work as it should be as it can be inherited from another style that is LTR than RTL.

Also I tried searching for `config.rtl` in the docs and it does not appear to exist in any documentation I found in Ren'Py unless I am blind to see it.

**Comment by Sudoku8** [comment]
Thank you, Bronya-Rand, for your response. I appreciate your insights. To clarify, my main objective is simply to align the poem text to the right side of the screen. This isn't about implementing full RTL support but about right-aligning the text for visual presentation, regardless of the script used.
