### ISSUE TITLE
Main menu background error

### ISSUE THREAD

**Issue by ErnDevDDLC** [GanstaKingofSA/DDLCModTemplate2.0#81]
**Describe the bug**
When opening the template, instead of the normal ddlc background, a white background is displayed.

**To Reproduce**
1: Open the template

2: Move from TOS screen to main menu

**Expected behavior**
See the original DDLC pink dots background

**Screenshots**
![image](https://github.com/Bronya-Rand/DDLCModTemplate2.0/assets/84817953/f9ac4ed6-8e9c-4e2d-8029-1bfff2a006d1)

**Comment by Bronya-Rand** [comment]
Nothing in the main menu has been changed in the template outside of adding the Credits button and swapping the DDLC logo for the 2.0 logo. Also I can't really see what you mean by `a white background is displayed.` as I see the normal DDLC menu that is to be expected.

**Comment by ErnDevDDLC** [comment]
I fixed it, it was a mistake I made, thanks anyway!
