### ISSUE TITLE
Dead links in README.md

### ISSUE THREAD

**Issue by edave64** [GanstaKingofSA/DDLCModTemplate2.0#83]
**Describe the bug**
The README.md links https://bronya-rand.github.io/information/guides/Installing-the-Mod-Template-Recent.html and https://bronya-rand.github.io/information/guides/Installing-the-Mod-Template-Legacy.html for Getting Started instructions, and those lead to 404 pages.

**Screenshots**
![Screen Shot 2024-10-15 at 22 47 11](https://github.com/user-attachments/assets/58fb0e62-82b3-45a4-beb0-65ebb95cac7e)

**Comment by Bronya-Rand** [comment]
Totally have forgotten about those pages ever since I made them a while ago. Prob gonna move them to the wiki at a point in time.

**Comment by Bronya-Rand** [comment]
Updated
